apiVersion: v1
kind: Secret
metadata:
  name: container-registry-credentials
  namespace: "{{ .Scaffold.ci_namespace }}"
type: kubernetes.io/basic-auth
stringData:
  # container registry credentials
  username: "<USERNAME>" # Your username goes here
  password: "<PASSWORD>" # Your password goes here
