apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Scaffold.git_provider_secret }}"
  namespace: "{{ .Scaffold.ci_namespace }}"
type: Opaque
stringData:
  provider.token: "<token>"   # Your github repository token
  webhook.secret: "<secret>"  # Your github webhook secret
