apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- application.yaml
- pac_repository.yaml

images:
- name: "{{ .Scaffold.container_image_name }}"
  newTag: "updated_from_ci"
